google:
  scopes:
    - admin.directory.user
    - admin.reports.audit.readonly
    - drive.file
    - drive.readonly
    - drive
    - gmail.send
    - gmail.readonly
    - gmail.compose
  audit:
    columns:
      - type
      - name
      - id
      - date
      - time
      - event
      - description
      - actor
      - address
      - value
  domain: NULL
logging:
  level: info
  format: text
  output: stdout
  log_file_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)d)"
  log_console_format: "%(asctime)s - %(message)s"
settings:
  save_on_exit: true
