google:
  scopes:
    - https://www.googleapis.com/auth/admin.directory.user
    - https://www.googleapis.com/auth/admin.reports.audit.readonly
  audit:
    columns:
      - type
      - name
      - id
      - date
      - time
      - event
      - description
      - actor
      - address
      - value
mitre:
  tactics:
    - collection
    - credential_access
    - defense_evasion
    - initial_access
logging:
  level: info
  format: text
  output: stdout
  log_file_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)d)"
  log_console_format: "%(asctime)s - %(message)s"
settings:
  save_on_exit: true
